CREATE TABLE IF NOT EXISTS payments (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    payment TEXT NOT NULL,
    price REAL NOT NULL,
    amount INTEGER NOT NULL DEFAULT 1,
    created DATE NOT NULL 
)